// Generated by CoffeeScript 1.10.0
var Promise, crypto, exec, fs, jsdom, readFile;

fs = require('fs');

crypto = require('crypto');

exec = require('child_process').exec;

jsdom = require('jsdom');

Promise = require('bluebird');

readFile = function(filepath, optional) {
  if (optional == null) {
    optional = false;
  }
  return function() {
    return new Promise(function(resolve, reject) {
      return fs.readFile(filepath, 'utf8', function(err, data) {
        if (err && !optional) {
          reject(err);
        }
        if (err) {
          data = '';
        }
        return resolve(data);
      });
    });
  };
};

module.exports = function(content) {
  var base_path, cpp_html, cpp_output, next, result;
  this.cacheable();
  next = this.async();
  base_path = this.resourcePath;
  cpp_html = base_path + '.html';
  cpp_output = base_path + '.output';
  result = '';
  return readFile(cpp_html)().then(function(html) {
    result += html;
    return null;
  }).then(readFile(cpp_output, 'optional')).then(function(output_content) {
    if (output_content.length) {
      result += "<pre class=\"program-output\" >" + output_content + "</pre>";
    }
    return null;
  }).then(function() {
    return next(null, result);
  })["catch"]((function(_this) {
    return function(err) {
      _this.emitError("Syntaxify went horribly wrong.");
      return next(err);
    };
  })(this));
};
